appName: BinAlerter
logLevel: DEBUG

scrape:
    calendar_url: https://ilforms.wiltshire.gov.uk/WasteCollectionDays/index
    address_url: https://ilforms.wiltshire.gov.uk/WasteCollectionDays/AddressList
    collection_url: https://ilforms.wiltshire.gov.uk/WasteCollectionDays/CollectionList

location:
    postcode: ******
    address: ******

pushover:
    api_token: ****** 
    clients:
        - ******

