version: "3"

services:
  binalerter:
    container_name: binalerter
    image: bmrussell/binalerter
    build:
      context: .
      dockerfile: ./Dockerfile

#    Config overrride if needed 
#      volumes:
#        - ./config/:/usr/src/BinAlerter/
    restart: unless-stopped
